### PR TITLE
Diagram plugins

### PR DESCRIPTION
**Pull request by kiwiroy**
## Summary
A plugin to render diagrams using [mermaid](https://mermaidjs.github.io).

## References

Issue #525

### CODE REVIEW

**Comment by kiwiroy** [comment]
I started a [Ditaa plugin](https://github.com/preaction/Statocles/compare/master...kiwiroy:diagram-plugins-2) also.

**Comment by preaction** [comment]
This looks great. I totally didn't know Mermaid could do Gantt charting, but this is great.

I like the idea of using a script link's text to add a bit of javascript to the header (or whereever the theme puts the JS), but we are going to need to test that all the themes handle that situation properly. There's another test, `t/theme/check.t` that tests all the themes. There's a `sub test_layout_content` that has tests that all themes must pass. Add a simple test there to make sure that the text version of a JS link is supported and this is good to go.

Thanks for the patch!

**Comment by preaction** [comment]
This still needs a test added to `t/theme/check.t`. Would you like me to add one so this can be merged?

**Comment by kiwiroy** [comment]
@preaction please go ahead.

**Comment by preaction** [comment]
This is added to `master` now. Thanks!

**Pull request closed without merging**
