### PR TITLE
Fix some problems on Windows and when RE metacharacters in path

### PR DESCRIPTION
**Pull request by mohawk2**
The `lib/Statocles/Util.pm` change is so that it can handle when there are single entities in eg `$^X` that have spaces, instead of just doing a `split` on whitespace. To do it truly truly properly would probably require `Text::ParseWords` and I didn't want to add a dep.

### CODE REVIEW

**Comment by preaction** [comment]
Looks good to me. There's some test failures in Travis, but I'm going to fix them by removing the different options for `die` from the `run_editor` subroutine, making there only be one exception: `Editor exited with non-zero status: $?`.

**Comment by djerius** [comment]
`Text::ParseWords` has been in core for a while:

```
% corelist Text::ParseWords

Data for 2018-02-20
Text::ParseWords was first released with perl 5
```

**Comment by mohawk2** [comment]
@djerius Long after, I've looked at this again and you're right of course! However, I don't want to change this code since `$ENV{EDITOR}` is inherently a string rather than an array thing, so this change needs to more or less stand as-is.

If it's any consolation, I remembered your advice when I made https://github.com/PDLPorters/extutils-f77/pull/1, as you might have inferred when you saw it (and kindly commented)!

**Comment by djerius** [comment]
I am consoled!

**Pull request merged**
